apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      env: dev
      platform: eks

resources:
  - ../../k8s
  - alb-ingress.yaml
  - externalname-services.yaml
  - external-secrets.yaml

images:
  - name: pamela001/payflow-wallet-api-gateway
    newName: 725094769583.dkr.ecr.us-east-1.amazonaws.com/payflow-wallet-api-gateway
    newTag: v2
  - name: pamela001/payflow-wallet-auth-service
    newName: 725094769583.dkr.ecr.us-east-1.amazonaws.com/payflow-wallet-auth-service
    newTag: v2
  - name: pamela001/payflow-wallet-frontend
    newName: 725094769583.dkr.ecr.us-east-1.amazonaws.com/payflow-wallet-frontend
    newTag: v3
  - name: pamela001/payflow-wallet-notification-service
    newName: 725094769583.dkr.ecr.us-east-1.amazonaws.com/payflow-wallet-notification-service
    newTag: v2
  - name: pamela001/payflow-wallet-transaction-service
    newName: 725094769583.dkr.ecr.us-east-1.amazonaws.com/payflow-wallet-transaction-service
    newTag: v2
  - name: pamela001/payflow-wallet-wallet-service
    newName: 725094769583.dkr.ecr.us-east-1.amazonaws.com/payflow-wallet-wallet-service
    newTag: v2

patches:
  - path: patch-configmap.yaml
  - path: patch-namespace-label.yaml
  - path: patch-frontend-service.yaml
  - path: patch-backup-pvc-storageclass.yaml

configMapGenerator:
  - name: edge-config
    literals:
      - WAF_WEB_ACL_ARN=PLACEHOLDER
      - ALB_LISTEN_PORTS=[{"HTTP":80}]
      - ALB_SSL_REDIRECT=443
      - ALB_CERT_ARN=PLACEHOLDER

vars:
  - name: WAF_WEB_ACL_ARN
    objref:
      kind: ConfigMap
      name: edge-config
      apiVersion: v1
    fieldref:
      fieldpath: data.WAF_WEB_ACL_ARN
  - name: ALB_LISTEN_PORTS
    objref:
      kind: ConfigMap
      name: edge-config
      apiVersion: v1
    fieldref:
      fieldpath: data.ALB_LISTEN_PORTS
  - name: ALB_SSL_REDIRECT
    objref:
      kind: ConfigMap
      name: edge-config
      apiVersion: v1
    fieldref:
      fieldpath: data.ALB_SSL_REDIRECT
  - name: ALB_CERT_ARN
    objref:
      kind: ConfigMap
      name: edge-config
      apiVersion: v1
    fieldref:
      fieldpath: data.ALB_CERT_ARN
