repos:
  - repo: local
    hooks:
      - id: gitleaks
        name: gitleaks
        entry: gitleaks detect --source . --no-git --no-banner --redact --exit-code 1
        language: system
        pass_filenames: false
        stages: [pre-commit]
