apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

  - configmaps/app-config.yaml
  - configmaps/db-migrations.yaml
  - secrets/db-secrets.yaml

  - deployments/api-gateway.yaml
  - deployments/auth-service.yaml
  - deployments/wallet-service.yaml
  - deployments/transaction-service.yaml
  - deployments/notification-service.yaml
  - deployments/frontend.yaml
  - deployments/redis.yaml

  - services/all-services.yaml

  - infrastructure/postgres.yaml
  - infrastructure/rabbitmq.yaml
  - infrastructure/metrics-server.yaml

  - ingress/http-ingress.yaml

  - autoscaling/hpa.yaml

  - jobs/db-migration-job.yaml
  - jobs/db-backup-cronjob.yaml
  - jobs/pushgateway-metrics.yaml
  - jobs/transaction-timeout-handler.yaml

  - policies/limit-range.yaml
  - policies/network-policies.yaml
  - policies/pod-disruption-budgets.yaml
  - policies/resource-quotas.yaml
